version: "3.8"

services:
  postgrest:
    image: postgrest/postgrest
    restart: unless-stopped
    # Expose post 3000 and access postgrest locally by uncommenting
    # the `ports` directive below
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://user:password@postgres:5432/db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: user
    links:
      - postgres:postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/scripts:/scripts

  dbmanage:
    container_name: dbmanage
    build:
      context: .
      dockerfile: ./dbmanage/Dockerfile
    volumes:
      - .:/app
      - ./dbmanage/data:/data
    command: bash -c "/app/dbmanage/dbmanage"
    environment:
      - DBMANAGE_DISCORD_TOKEN
      - DBMANAGE_ADMIN_CHAN=1006934337612173413
      - DBMANAGE_DB_PATH=/data
      - DBMANAGE_PG_PORT=3000
    restart: unless-stopped

  embed:
    container_name: embed
    build:
      context: .
      dockerfile: ./embed/Dockerfile
    volumes:
      - .:/app
    command: bash -c "go build /app/embed && /app/embed/embed"
    restart: unless-stopped

volumes:
  postgres-data: {}
